#include "axys/initrd.h"
#include "axys/printf.h"
#include "axys/string.h"
#include "axys/vfs.h"

struct axys_initrd_entry {
    const char *path;
    const axys_uint8_t *start;
    const axys_uint8_t *end;
};

/* Generated by the Makefile (build/initrd.S), NULL-terminated. */
extern const struct axys_initrd_entry axys_initrd_table[];

int axys_initrd_install(void)
{
    int count = 0;

    for (const struct axys_initrd_entry *e = axys_initrd_table; e->path != AXYS_NULL; ++e) {
        char dir[AXYS_VFS_MAX_PATH];
        axys_size_t length = axys_strlen(e->path);
        axys_size_t slash = 0;
        axys_vfs_node_t node;
        axys_size_t size = (axys_size_t)(e->end - e->start);

        if (length >= sizeof(dir)) {
            return -1;
        }
        for (axys_size_t i = 0; i < length; ++i) {
            if (e->path[i] == '/') {
                slash = i;
            }
        }
        if (slash > 0) {
            axys_memcpy(dir, e->path, slash);
            dir[slash] = '\0';
            if (axys_vfs_mkdirs(dir) != 0) {
                return -1;
            }
        }
        node = axys_vfs_create_as(e->path, AXYS_VFS_FILE, 0755u, 0, 0); /* programs: rwxr-xr-x */
        if (node < 0 || axys_vfs_pwrite(node, 0, e->start, size) != (axys_int32_t)size) {
            return -1;
        }
        ++count;
    }
    return count;
}

static int put_file(const char *path, axys_uint32_t mode, const char *text)
{
    axys_vfs_node_t node = axys_vfs_lookup(path);

    if (node >= 0) {
        return 0; /* already there (e.g. restored from disk): keep it */
    }
    node = axys_vfs_create_as(path, AXYS_VFS_FILE, mode, 0, 0);
    if (node < 0 || axys_vfs_write(node, text, axys_strlen(text)) < 0) {
        return -1;
    }
    return 1;
}

int axys_initrd_install_defaults(void)
{
    int rc = 0;

    rc |= put_file("/etc/hostname", 0644u, "axys\n") < 0;
    rc |= put_file("/etc/passwd", 0644u, "root:x:0:0:root:/root:/sbin/init\nuser:x:1000:1000:user:/home/user:/sbin/init\n") < 0;
    rc |= put_file("/etc/group", 0644u, "root:x:0:\nusers:x:1000:user\n") < 0;
    rc |= put_file("/etc/motd", 0644u, "Welcome to axysOS.\n") < 0;
    rc |= put_file("/etc/secret", 0600u, "root-only data\n") < 0;
    if (axys_vfs_lookup("/home/user") < 0 &&
        axys_vfs_create_as("/home/user", AXYS_VFS_DIR, 0755u, 1000, 1000) < 0) {
        rc = 1;
    }
    return rc == 0 ? 0 : -1;
}
