"""
Emit the isr/irq stub address table consumed by axys_idt_init.

The table is indexed by vector number, so entry N must be the address of the
stub that pushes N. It lives in .rodata next to the stubs themselves.

Run:  python3 tools/gen_stub_table.py > /tmp/table.txt
"""

print("/*")
print(" * Stub addresses indexed by vector number: entry N is the handler that")
print(" * pushes N, so axys_idt_init can install the table wholesale.")
print(" *")
print(" * Generated by tools/gen_stub_table.py.")
print(" */")
print(".global axys_isr_stub_table")
print("axys_isr_stub_table:")
for n in range(0, 32):
    print("    .quad isr%d" % n)
for n in range(32, 48):
    print("    .quad irq%d" % (n - 32))
for n in range(48, 256):
    print("    .quad isr%d" % n)
